// Generates www/generated/env.js from the same config-driven env as capacitor.config.ts.
// Injects the cabinet URL into the LOCAL shell/fallback pages (index.html, error.html)
// so the loading redirect and the offline "Retry" button know where the cabinet is —
// without hardcoding the host anywhere in committed source.
//
// Run automatically by `npm run sync|add:android|add:ios`; output is gitignored.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');

// Minimal .env loader (avoids importing dotenv from an .mjs standalone run).
function loadEnv() {
  const envPath = resolve(root, '.env');
  if (!existsSync(envPath)) return;
  for (const line of readFileSync(envPath, 'utf8').split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
    if (!m) continue;
    const [, key, rawVal] = m;
    if (process.env[key] === undefined) {
      process.env[key] = rawVal.replace(/^["']|["']$/g, '');
    }
  }
}

loadEnv();

const env = (process.env.CAP_ENV ?? 'staging').toLowerCase();
const hosts = {
  staging: process.env.CAP_URL_STAGING,
  prod: process.env.CAP_URL_PROD,
};
const url = hosts[env];

if (!url) {
  console.error(
    `[gen-web-env] No cabinet URL for CAP_ENV="${env}". ` +
      `Set CAP_URL_STAGING / CAP_URL_PROD in mobile/.env (copy .env.example).`,
  );
  process.exit(1);
}

const outDir = resolve(root, 'www', 'generated');
mkdirSync(outDir, { recursive: true });

const banner = '// AUTO-GENERATED by scripts/gen-web-env.mjs — do not edit, do not commit.\n';
const body = `window.__CABINET_URL__ = ${JSON.stringify(url)};\nwindow.__CABINET_ENV__ = ${JSON.stringify(env)};\n`;
writeFileSync(resolve(outDir, 'env.js'), banner + body, 'utf8');

console.log(`[gen-web-env] wrote www/generated/env.js  (env=${env}, url=${url})`);
