<?php

declare(strict_types=1);

/**
 * Generate the canonical inventory of env() keys read by config/*.php.
 *
 * Output is platform-stable: config files are scanned in path order, locations
 * are sorted, and key order uses SORT_STRING (not locale-dependent SORT_NATURAL).
 *
 * Usage:
 *   php scripts/generate_env_inventory.php
 *   php scripts/generate_env_inventory.php --check
 */
$root = dirname(__DIR__);
$outputPath = $root.'/docs/ENVIRONMENT_VARIABLES.md';
$check = in_array('--check', $argv, true);

/** @var array<string, list<array{path: string, line: int, hasDefault: bool, default: string}>> $occurrences */
$occurrences = [];

$configFiles = [];
$iterator = new RecursiveIteratorIterator(
    new RecursiveDirectoryIterator($root.'/config', FilesystemIterator::SKIP_DOTS)
);

foreach ($iterator as $file) {
    if (! $file->isFile() || $file->getExtension() !== 'php') {
        continue;
    }

    $relativePath = str_replace('\\', '/', substr($file->getPathname(), strlen($root) + 1));
    $configFiles[] = $relativePath;
}

// Deterministic scan order (RecursiveDirectoryIterator order differs by OS/FS).
sort($configFiles, SORT_STRING);

foreach ($configFiles as $relativePath) {
    $tokens = token_get_all((string) file_get_contents($root.'/'.$relativePath));
    $count = count($tokens);

    for ($i = 0; $i < $count; $i++) {
        $token = $tokens[$i];
        if (! is_array($token) || $token[0] !== T_STRING || strtolower($token[1]) !== 'env') {
            continue;
        }

        $open = nextMeaningfulToken($tokens, $i + 1);
        if ($open === null || $tokens[$open] !== '(') {
            continue;
        }

        $keyIndex = nextMeaningfulToken($tokens, $open + 1);
        $keyToken = $keyIndex !== null ? $tokens[$keyIndex] : null;
        if (! is_array($keyToken) || $keyToken[0] !== T_CONSTANT_ENCAPSED_STRING) {
            continue;
        }

        $key = stripcslashes(substr($keyToken[1], 1, -1));
        if (! preg_match('/^[A-Z][A-Z0-9_]*$/', $key)) {
            continue;
        }

        [$hasDefault, $default] = envDefault($tokens, $keyIndex + 1);
        $occurrences[$key][] = [
            'path' => $relativePath,
            'line' => $token[2],
            'hasDefault' => $hasDefault,
            'default' => $default,
        ];
    }
}

$entries = [];
foreach ($occurrences as $key => $rows) {
    // Stable primary: path then line (not discovery order).
    usort($rows, static function (array $a, array $b): int {
        return [$a['path'], $a['line']] <=> [$b['path'], $b['line']];
    });

    $primary = $rows[0];
    $locations = [];
    foreach ($rows as $row) {
        $locations[] = $row['path'].':'.$row['line'];
    }
    $locations = array_values(array_unique($locations));

    $entries[$key] = [
        'category' => classify($key, $primary['hasDefault'], $primary['default']),
        'default' => $primary['hasDefault'] ? normalizeDefault($primary['default']) : '—',
        'locations' => $locations,
    ];
}

ksort($entries, SORT_STRING);

$lines = [
    '# Environment variable inventory',
    '',
    '<!-- Generated by scripts/generate_env_inventory.php; do not edit by hand. -->',
    '',
    'This inventory covers every `env()` key read under `config/`. Run `php scripts/generate_env_inventory.php` after changing configuration. CI runs the same command with `--check` and rejects undocumented keys.',
    '',
    'Classification is deterministic: feature switches first, then credentials/secrets, then keys without a usable default as required, and all remaining keys as optional. A secret may still be conditionally required by its feature.',
    '',
    '| Key | Class | Default | Config location |',
    '|---|---|---|---|',
];

foreach ($entries as $key => $entry) {
    $locations = implode('<br>', $entry['locations']);
    $lines[] = sprintf(
        '| `%s` | %s | `%s` | %s |',
        $key,
        $entry['category'],
        escapeCell($entry['default']),
        $locations,
    );
}

$rendered = implode("\n", $lines)."\n";

if ($check) {
    $current = is_file($outputPath) ? (string) file_get_contents($outputPath) : '';
    // Normalize CRLF so Windows working trees still match LF-only CI output.
    $current = str_replace("\r\n", "\n", $current);
    if (! hash_equals($rendered, $current)) {
        fwrite(STDERR, "Environment inventory is stale. Run: php scripts/generate_env_inventory.php\n");
        exit(1);
    }

    fwrite(STDOUT, 'Environment inventory is current ('.count($entries)." keys).\n");
    exit(0);
}

file_put_contents($outputPath, $rendered);
fwrite(STDOUT, 'Wrote '.count($entries).' keys to '.$outputPath.".\n");

/** @param array<int, array{int, string, int}|string> $tokens */
function nextMeaningfulToken(array $tokens, int $start): ?int
{
    for ($i = $start, $count = count($tokens); $i < $count; $i++) {
        if (! is_array($tokens[$i]) || ! in_array($tokens[$i][0], [T_WHITESPACE, T_COMMENT, T_DOC_COMMENT], true)) {
            return $i;
        }
    }

    return null;
}

/**
 * @param  array<int, array{int, string, int}|string>  $tokens
 * @return array{bool, string}
 */
function envDefault(array $tokens, int $start): array
{
    $depth = 1;
    $collect = false;
    $default = '';

    for ($i = $start, $count = count($tokens); $i < $count; $i++) {
        $text = is_array($tokens[$i]) ? $tokens[$i][1] : $tokens[$i];

        if ($text === '(' || $text === '[') {
            $depth++;
        } elseif ($text === ')' || $text === ']') {
            $depth--;
            if ($depth === 0) {
                break;
            }
        } elseif ($text === ',' && $depth === 1 && ! $collect) {
            $collect = true;

            continue;
        }

        if ($collect) {
            $default .= $text;
        }
    }

    return [$collect, trim($default)];
}

function classify(string $key, bool $hasDefault, string $default): string
{
    if (preg_match('/(?:^|_)(?:ENABLED|ENABLE|DISABLED|FEATURE|PILOT)$/', $key)) {
        return 'feature-flag';
    }

    if (preg_match('/(?:SECRET|TOKEN|PASSWORD|PRIVATE_KEY|API_KEY|SIGNING_KEY|CREDENTIAL)/', $key)) {
        return 'secret';
    }

    if (! $hasDefault || in_array(strtolower(trim($default)), ['', 'null'], true)) {
        return 'required';
    }

    return 'optional';
}

function normalizeDefault(string $default): string
{
    $default = preg_replace('/\s+/', ' ', trim($default)) ?? '';

    return mb_strlen($default) > 70 ? mb_substr($default, 0, 67).'…' : $default;
}

function escapeCell(string $value): string
{
    return str_replace(['|', '`'], ['\\|', '\\`'], $value);
}
